// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rotmzbpxjzjqajpedigx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvdG16YnB4anpqcWFqcGVkaWd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NzYxMDAsImV4cCI6MjA2OTA1MjEwMH0.EZxY0sD3MoDpJKE07C7yCNwAx2-Z_dNNs1NJxO1bnvw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});